config/routes.rb
Inventory::Application.routes.draw do
  resources :listings

  resources :lists

  resources :placements

  resources :containers do
    member do
      post 'list_contents_of'
    end
  end

  resources :items

  devise_for :users do
    match '/logout' => 'devise/sessions#destroy', :as => :logout
  end
  
  resources :users

  root :to => 'items#index'

end

app/models/container.rb
class Container < ActiveRecord::Base
  belongs_to :user
  has_many :placements
  has_many :items, :through => :placements
  
  attr_accessible :image, :name
  
  mount_uploader :image, ImageUploader
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @containers }
    end
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
    @container = Container.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @container }
    end
  end
  
  def list_contents_of
    @container = Container.find params[:id]
    @list = List.new :name => "#{current_user.first_name}'s list of items in #{@container.name}", :user => current_user
    @container.items.each do |item|
      @list.items << item
    end
    @list.save
    redirect_to @list
  end

  # GET /containers/new
  # GET /containers/new.json
  def new
    @container = Container.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @container }
    end
  end

  # GET /containers/1/edit
  def edit
    @container = Container.find(params[:id])
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(params[:container])
    @container.user = current_user

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render json: @container, status: :created, location: @container }
      else
        format.html { render action: "new" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /containers/1
  # PUT /containers/1.json
  def update
    @container = Container.find(params[:id])

    respond_to do |format|
      if @container.update_attributes(params[:container])
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container = Container.find(params[:id])
    @container.destroy

    respond_to do |format|
      format.html { redirect_to containers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/views/containers/_form.html.erb
<%= form_for(@container) do |f| %>
  <% if @container.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
      <% @container.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<h1>Editing container</h1>

<%= render 'form' %>

<%= link_to 'Show', @container %> |
<%= link_to 'Destroy', @container, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/containers/index.html.erb
<% @containers.each do |container| %>
  <%= div_for container do %>
    <%= link_to_name container %>
    <%= image_tag container.image, :width => 300 %>
  <% end %>
<% end %>

<br />

<%= link_to 'New Container', new_container_path %>

app/views/containers/new.html.erb
<h1>New container</h1>

<%= render 'form' %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @container.name %>
</h2>

<p>
  <%= image_tag @container.image, :width => 280 %>
</p>

<div id="placements">
  <% @container.placements.each do |placement| %>
    <%= div_for placement do %>
      <%= link_to_name placement.item %>
      <%= image_tag placement.item.image, :width => 180 %>
    <% end %>
  <% end %>
</div>


<%= link_to 'Create list from contents', list_contents_of_container_path(@container), :method => :post %> |
<%= link_to 'Edit', edit_container_path(@container) %> |
<%= link_to 'Back', containers_path %>